name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3
    
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
    
    - name: Install dependencies
      run: |
        pip install mlflow scikit-learn pandas numpy

    - name: Setup MLflow DB
      run: |
        mlflow migrate-filestore --source ./mlruns --destination sqlite:///mlflow.db
    
    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local
      env:
        MLFLOW_TRACKING_URI: sqlite:///mlflow.db
