name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3
    
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
    
    - name: Install dependencies
      run: |
        pip install mlflow scikit-learn pandas numpy
    
    - name: Run MLflow Project
      run: |
        python MLProject/modelling.py
